# Generated by Django 2.2.5 on 2021-03-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connect',
            name='contact',
        ),
    ]
